cv_generator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('pdf.urls', 'pdf'), namespace='pdf')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pdf/urls.py
from django.urls import path

from .views import ProfileView
from .views import ResumeListView, ResumeView
from .views import GeneratePdf


urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
    path('resumes', ResumeListView.as_view(), name='resumes'),
    path('resume/<str:slug>', ResumeView.as_view(), name='resume-details'),
    path('download/<str:slug>', GeneratePdf.as_view(), name='resume-download'),

]

pdf/models.py
from time import time

from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown import markdown


def get_slug(s):
    new_slug = slugify(s, allow_unicode=True)
    return new_slug + '-' + str(int(time()))


class Profile(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    phone = models.CharField(max_length=200)
    summary = models.TextField(max_length=2000)
    linkedin_link = models.URLField(blank=True)
    facebook_link = models.URLField(blank=True)
    git_link = models.URLField(blank=True)
    skills = models.TextField(max_length=1000, blank=True)

    experience = models.TextField()
    education = models.TextField(max_length=2000)

    interests = models.TextField(max_length=1000, blank=True)
    awards_and_certifications = models.TextField(max_length=2000, blank=True)

    url = models.SlugField(max_length=200, unique=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.url = get_slug(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('pdf:resume-details', kwargs={'slug': self.url})

    def get_markdown_skills(self):
        return mark_safe(markdown(self.skills, safe_mode='escape'))

    def get_markdown_experience(self):
        return mark_safe(markdown(self.experience, safe_mode='escape'))

    def get_markdown_education(self):
        return mark_safe(markdown(self.education, safe_mode='escape'))

    def get_markdown_interests(self):
        return mark_safe(markdown(self.interests, safe_mode='escape'))

    def get_markdown_awards_and_certifications(self):
        return mark_safe(markdown(self.awards_and_certifications, safe_mode='escape'))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'CV Profile'
        verbose_name_plural = 'CV Profiles'
        ordering = ['-created']

pdf/forms.py
from django import forms
from pagedown.widgets import PagedownWidget

from .models import Profile


class ProfileForm(forms.ModelForm):
    skills = forms.CharField(widget=PagedownWidget)
    experience = forms.CharField(widget=PagedownWidget)
    education = forms.CharField(widget=PagedownWidget)
    interests = forms.CharField(widget=PagedownWidget)
    awards_and_certifications = forms.CharField(widget=PagedownWidget)

    class Meta:
        model = Profile
        exclude = ('url',)

        widgets = {
            'name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'John Doe', 'required': 'required'}),
            'email': forms.TextInput(
                attrs={'class': 'form-control', 'style': "margin-top: 15px;", 'placeholder': 'demo@gmail.com'}),
            'phone': forms.TextInput(
                attrs={'class': 'form-control', 'style': "margin-top: 15px;", 'placeholder': '+38 099 170 7777'}),
            'summary': forms.Textarea(
                attrs={'class': 'form-control', 'cols': "100", 'rows': "10",
                       'placeholder': 'Write something about you'}),
            'linkedin_link': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'https://www.linkedin.com/in/valentyna-lysenok/',
                       'required': 'required'}),
            'git_link': forms.TextInput(
                attrs={'class': 'form-control', 'style': "margin-top: 15px;",
                       'placeholder': 'https://github.com/ValentinaLV'}),
            'facebook_link': forms.TextInput(
                attrs={'class': 'form-control', 'style': "margin-top: 15px;",
                       'placeholder': 'https://www.facebook.com/tinalysenok'}),

        }

pdf/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic.base import View

from .forms import ProfileForm
from .models import Profile
from .utils import Render, posts_pagination


class ProfileView(View):
    def get(self, request):
        profile_form = ProfileForm()
        return render(request, 'base.html', {
            'form': profile_form
        })

    def post(self, request):
        profile_form = ProfileForm(request.POST)
        if profile_form.is_valid():
            messages.success(request, "Your CV was successfully created)")
            profile_form.save()
            return redirect('pdf:resumes')
        else:
            messages.error(request, "Your CV wasn't created...")


class ResumeListView(View):
    def get(self, request):
        return render(request, 'resume_list.html',
                      context=posts_pagination(request))


class ResumeView(View):
    def get(self, request, slug):
        resume = Profile.objects.get(url=slug)
        return render(request, 'resume.html', {
            'resume': resume
        })


class GeneratePdf(View):
    def get(self, request, slug):
        user_profile = Profile.objects.get(url=slug)
        params = {
            'resume': user_profile,
            'request': request
        }
        return Render.render('resume.html', params)

pdf/templates/resume.html
{% extends 'base.html' %}

{% block navbar %}
{% endblock %}

{% block content %}
    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="about">
        <div class="w-100">
            <div class="container">
                <div class="row m-5">
                    <div class="col-md-12">
                        <h3>{{ resume.name }}</h3>
                        <h3>{{ resume.email }}</h3>
                        <h3>{{ resume.phone }}</h3>
                        <div class="social-icons">
                            <div>
                                <a href="{{ resume.linkedin_link }}"><i class="fab fa-linkedin-in"></i></a>
                                <span>{{ resume.linkedin_link }}</span>
                            </div>
                            <div>
                                <a href="{{ resume.git_link }}"><i class="fab fa-github"></i></a>
                                <span>{{ resume.git_link }}</span>
                            </div>
                            <div>
                                <a href="{{ resume.facebook_link }}"><i class="fab fa-facebook-f"></i></a>
                                <span>{{ resume.facebook_link }}</span>
                            </div>
                        </div>
                        <hr/>
                        <br/>
                        <h4>Summary</h4>
                        <p>{{ resume.summary }}</p>
                        <hr/>
                        <h4>Skills</h4>
                        <p>{{ resume.get_markdown_skills }}</p>
                        <hr/>
                        <h4>Previous Work Experience</h4>
                        <p>{{ resume.get_markdown_experience }}</p>
                        <hr/>
                        <h4>Education</h4>
                        <p>{{ resume.get_markdown_education }}</p>
                        <hr/>
                        <h4>Interests</h4>
                        <p>{{ resume.get_markdown_interests }}</p>
                        <hr/>
                        <h4>Awards & Certifications</h4>
                        <p>{{ resume.get_markdown_awards_and_certifications }}</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

pdf/templates/resume_list.html
{% extends 'base.html' %}

{% block content %}

    <section class="p-3 p-lg-5">
        <form action="{% url 'pdf:resumes' %}" method="GET" class="form-inline justify-content-center">
            <div class="form-group">
                <label>
                    <input type="text" class="form-control" name="search"
                           value="{{ request.get.search }}"
                           placeholder="Search...">
                </label>
                <button type="submit" class="btn btn-warning post-search-btn">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </form>
    </section>

    <section class="p-3 p-lg-5 d-flex align-items-center">
        <div class="w-100">
            <div class="container">
                <div class="row m-5">
                    <div class="col-md-12">
                        {% for resume in page_obj.object_list %}
                            <div class="col-md-12">
                                <h4>{{ resume.name }} - {{ resume.created }}</h4>
                                <span>
                                    <a href="{{ resume.get_absolute_url }}" class="btn btn-warning"
                                       role="button">View CV</a>
                                </span>
                                <span><a href="{% url 'pdf:resume-download' resume.url %}" class="btn btn-info"
                                         role="button">Download CV</a></span>
                                <hr>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="pb-lg-5 text-center">

        <span class="page-item" style="{% if not prev_url %} opacity: 0.3; {% endif %}">
            <a href="{{ prev_url }}" class="btn-default page-link" style="display: inline; color: #343a40;">
                <span aria-hidden="true">←</span> Previous
            </a>
        </span>

        {% for n in page_obj.paginator.page_range %}

            {% if page_obj.number == n %}
                <span class="page-item">
                    <a href="?page={{ n }}" class="btn-default page-link"
                       style="display: inline; background-color: #17a2b8; color: #343a40;">{{ n }}</a>
                </span>

            {% elif n > page_obj.number|add:-2 and n < page_obj.number|add:2 %}
                <span class="page-item">
                    <a href="?page={{ n }}" class="btn-default page-link"
                       style="display: inline; color: #343a40;">{{ n }}</a>
                </span>
            {% endif %}

        {% endfor %}

        <span class="page-item" style="{% if not next_url %} opacity: 0.3; {% endif %}">
                <a href="{{ next_url }}" class="btn-default page-link" style="display: inline; color: #343a40;">
                   Next<span aria-hidden="true">→</span></a>
            </span>
    </div>
{% endblock %}

templates/base.html
{% load static %}


{% block head_extra %}
    {{ form.media }}
{% endblock %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>CVs Generator</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/resume.min.css' %}" rel="stylesheet">

</head>

<body id="page-top">

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">
            <span class="d-block d-lg-none">CV Generator</span>
            <span class="d-none d-lg-block">
        <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'img/logo.jpg' %}" alt="">
      </span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item" style="margin-bottom: 10px;">
                    <a href="{% url 'pdf:resumes' %}" class="btn btn-outline-warning">Profiles</a>
                </li>
                <li class="nav-item" style="margin-bottom: 10px;">
                    <a href="{% url 'pdf:profile' %}" class="btn btn-outline-info">Generate CV</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#skills">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#education">Education</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#interests">Interests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#awards">Awards</a>
                </li>
            </ul>
        </div>
        <div class="fh5co-footer">
            <p><span>&copy; 2020 All Rights Reserved.
                <a href="https://github.com/ValentinaLV/cv_generator" style="color: #868e96;">ValentinaLV</a>
            </span>
        </div>
    </nav>
{% endblock %}

<div class="container-fluid p-0">
    {% block content %}
        <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="about">
            <div class="w-100">
                <div class="container">
                    <div class="row m-5">
                        <div class="col-md-12">
                            <h1>CV Generator</h1>
                            <h3>using Markdown and simple input</h3>
                            <hr>
                        </div>
                    </div>
                    <div class="row m-5">
                        <div class="col-md-12">
                            <h4>Please fill out your details</h4>

                        </div>
                    </div>
                    <div class="row m-5">
                        <div class="col-md-7">

                            <form method="POST">
                                {% csrf_token %}
                                {% for field in form %}

                                    {% if field.name == 'skills' %}
                                        <h2 class="mb-5" id="skills">Skills</h2>
                                    {% elif field.name == 'experience' %}
                                        <h2 class="mb-5" id="experience">Experience</h2>
                                    {% elif field.name == 'education' %}
                                        <h2 class="mb-5" id="education">Education</h2>
                                    {% elif field.name == 'interests' %}
                                        <h2 class="mb-5" id="interests">Interests</h2>
                                    {% elif field.name == 'awards_and_certifications' %}
                                        <h2 class="mb-5" id="awards">Awards &amp; Certifications</h2>
                                    {% endif %}

                                    <div class="form-group">
                                        {{ field.label }}
                                        {{ field }}
                                    </div>

                                    <hr class="m-0">

                                {% endfor %}
                                <button type="submit" class="btn btn-warning">Submit</button>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </section>

        <hr class="m-0">
    {% endblock %}
</div>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for this template -->
<script src="{% static 'js/resume.min.js' %}"></script>

</body>

</html>